name: flutter_boilerplate
description: "Flutter boilerplate."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  file_picker: ^6.1.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  intl:
  connectivity_plus:
  firebase_core:
  flutter_local_notifications:
  path_provider:
  url_strategy:
  cached_network_image:
  image_picker:
  firebase_messaging:
  path:
  dartdoc:
  fluttertoast:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
